### ISSUE TITLE
Can't get app work

### ISSUE THREAD

**Issue by joaco1977** [start-angular/ani-angular-2#2]
Hi, I cloned the project and follow the steps and cant get app working.
Maybe is not an issue for you, but I 'm having this message "Cannot GET /" , after installed and ran the app.
Do you know what could be wrong?

Thanks!

**Comment by nkmdev** [comment]
in the development mode the baseurl is http://localhost:8080/dist/dev/

**Comment by joaco1977** [comment]
Yes, ok thanks!
