### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by iliagerman** [start-angular/ani-angular-2#7]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! SB-Admin-BS4-Angular-2@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SB-Admin-BS4-Angular-2@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SB-Admin-BS4-Angular-2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SB-Admin-BS4-Angular-2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SB-Admin-BS4-Angular-2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Dev\ani-angular-2-master\npm-debug.log

any ideas?

**Comment by nkmdev** [comment]
Is there any error in npm install?

**Comment by iliagerman** [comment]
no

**Comment by nkmdev** [comment]
Before doing following step just re clone the project and try
OR
try following steps:
1: MSBuild Tool 2013 use `https://www.microsoft.com/en-in/download/confirmation.aspx?id=40760`
2: `ts-node` installed globally  `npm install -g ts-node` 
3: Run the Command Prompt  with administrator privileges.
4: npm install —msvs_version=2013
5: npm start

**Comment by RbkGh** [comment]
in my case I had to install gulp and highchart globally using admin privileges on windows and import into the project,afterwards,npm start worked :Below are the steps,using admin priveleges
`1.npm install -g gulp
 2.npm install -g highchart
 3.Now cd into the root of ani-angular-2.
 4.npm install gulp --save
 5.npm install highchart --save
 6.npm start` 
This worked for me.

**Comment by iliagerman** [comment]
Thanks a lot

**Comment by PrithivirajS** [comment]
how to resolve this issue, when i was run serve.prod

Failed at the SB-Admin-BS4-Angular-2@0.0.0 serve.prod script.

 This is probably not a problem with npm. There is likely additional logging output above.

 node ---v6.12.0
npm ---5.5.1
